source :gemcutter

gem "sinatra", ">= 2.2.3"
gem "choice"
gem "json"
gem "postgres", "=0.7.9.2008.01.28"
gem "haml"
gem "bluecloth"
gem "text"
gem "levenshtein"
gem "hpricot"
gem "activesupport"
gem "htmlentities"
gem "text"
gem "chronic"
