source :gemcutter

gem "sinatra", ">= 2.0.2"
gem "choice"
gem "json", ">= 1.5.5"
gem "postgres", "=0.7.9.2008.01.28"
gem "haml", ">= 5.0.0"
gem "bluecloth"
gem "text"
gem "levenshtein"
gem "hpricot"
gem "activesupport", ">= 3.2.22"
gem "htmlentities"
gem "text"
gem "chronic"
